### ISSUE TITLE
multiple errors / strange things

### ISSUE THREAD

**Issue by firelook** [dna909/ioBroker.homeconnect#10]
these are my logs, hope will help : 
`

  |   |   |  
-- | -- | -- | --
homeconnect.0 | 2019-01-17 05:46:43.930 | info | starting. Version 0.0.6 in C:/iobroker/node_modules/iobroker.homeconnect, node: v6.11.3
host.Obelix | 2019-01-17 05:46:42.765 | info | instance system.adapter.homeconnect.0 started with pid 3688
host.Obelix | 2019-01-17 05:46:12.758 | info | Restart adapter system.adapter.homeconnect.0 because enabled
host.Obelix | 2019-01-17 05:46:12.758 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at ClientRequest.emit (events.js:188:7)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at emitOne (events.js:96:13)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at ClientRequest.g (events.js:292:16)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:155:9)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at EventSource.emit (events.js:188:7)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at emitOne (events.js:96:13)
Caught | 2019-01-17 05:46:12.757 | error | by controller[0]: at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:265:27)
Caught | 2019-01-17 05:46:12.756 | error | by controller[0]: Error: 429
homeconnect.0 | 2019-01-17 05:46:12.736 | info | cleaned everything up...
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at ClientRequest.emit (events.js:188:7)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at ClientRequest.g (events.js:292:16)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:155:9)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at EventSource.emit (events.js:188:7)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:265:27)
homeconnect.0 | 2019-01-17 05:46:12.736 | error | Error: 429
homeconnect.0 | 2019-01-17 05:46:12.736 | error | uncaught exception: 429
homeconnect.0 | 2019-01-17 05:46:12.729 | error | FEHLER
homeconnect.0 | 2019-01-17 05:46:12.728 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-01-17 05:46:12.727 | error | 429
homeconnect.0 | 2019-01-17 05:46:12.330 | info | starting. Version 0.0.6 in C:/iobroker/node_modules/iobroker.homeconnect, node: v6.11.3
host.Obelix | 2019-01-17 05:46:10.529 | info | instance system.adapter.homeconnect.0 started with pid 2976
host.Obelix | 2019-01-17 05:45:40.520 | info | Restart adapter system.adapter.homeconnect.0 because enabled
host.Obelix | 2019-01-17 05:45:40.520 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at ClientRequest.emit (events.js:188:7)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at emitOne (events.js:96:13)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at ClientRequest.g (events.js:292:16)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:155:9)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at EventSource.emit (events.js:188:7)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at emitOne (events.js:96:13)
Caught | 2019-01-17 05:45:40.519 | error | by controller[1]: at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:265:27)
Caught | 2019-01-17 05:45:40.518 | error | by controller[1]: Error: 429
homeconnect.0 | 2019-01-17 05:45:40.495 | info | cleaned everything up...
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at ClientRequest.emit (events.js:188:7)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at ClientRequest.g (events.js:292:16)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:155:9)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at EventSource.emit (events.js:188:7)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:265:27)
homeconnect.0 | 2019-01-17 05:45:40.494 | error | Error: 429
homeconnect.0 | 2019-01-17 05:45:40.494 | error | uncaught exception: 429
homeconnect.0 | 2019-01-17 05:45:40.491 | error | FEHLER
homeconnect.0 | 2019-01-17 05:45:40.491 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-01-17 05:45:40.490 | error | 429
homeconnect.0 | 2019-01-17 05:45:40.137 | info | Accestoken renewed...
homeconnect.0 | 2019-01-17 04:45:39.906 | info | Accestoken renewed...
homeconnect.0 | 2019-01-17 03:45:39.889 | info | Accestoken renewed...
homeconnect.0 | 2019-01-17 02:45:39.777 | info | Accestoken renewed...
homeconnect.0 | 2019-01-17 01:45:39.586 | info | Accestoken renewed...
host.Obelix | 2019-01-17 01:40:18.739 | info | Delete log file iobroker.2019-01-10.log
homeconnect.0 | 2019-01-17 01:15:11.166 | error | undefined
homeconnect.0 | 2019-01-17 01:15:02.717 | error | undefined
homeconnect.0 | 2019-01-17 01:15:02.712 | error | undefined
homeconnect.0 | 2019-01-17 01:15:02.092 | error | undefined
homeconnect.0 | 2019-01-17 00:45:39.591 | info | Accestoken renewed...
homeconnect.0 | 2019-01-17 00:15:02.204 | error | undefined

`

**Comment by dna909** [comment]
There seemed to be too many requests in one day.
The adapter returns error 429:

429 Too Many Requests E.g. the number of requests for a specific endpoint exceeded the quota of the client

Unfortunately there is a limit of 1000 requests per day.
In this case it only helps to wait and the next day at the latest it should work again. Normally this should not happen, because hardly any data is polled.
Probably the adapter was restarted too often.

The adapter is also more or less still in alpha state.
Really productive you cannot use it yet.

As soon as I find time again, I will continue to work on it.

**Comment by firelook** [comment]
First Thank you foryour time !

I do understand it is alpha but it is very very use full !

I gave you my log to help you (I hope ...)
on my side I did nothing, the program is working with no manual intervention. So following your remark, it seems you have a glitch somewere

By the way, it seems you have corrected the "reconnect" or "loss connection to the token"

if you need more informations please asked

**Comment by firelook** [comment]
do you want more errors (seems the same problem) or is it ok ?

**Comment by firelook** [comment]
I have tested since few more day
1/ works better
2/ limit => after a crash and a reboot seems ok no request to reconnect BUT doesn't work
3/ after a reboot => seems ok but no way to say if it is connect or not
