### ISSUE TITLE
Crash "Cannot read property indexOf of null"

### ISSUE THREAD

**Issue by Garfonso** [dna909/ioBroker.homeconnect#16]
Hi,

today I added my first device, a dryer, to my homeconnect account. I did set up everything during the weekend already and had the "empty" account connected with ioBroker and it seemed to work fine (although I could not control anything, obviously).

But after adding the dryer the adapter now continously crashes with the attached log.
[homeconnectAdapterCrash.txt](https://github.com/dna909/ioBroker.homeconnect/files/3383913/homeconnectAdapterCrash.txt)

**Comment by TA2k** [comment]
Hi
please install from the github url and restart the instance.

**Comment by Garfonso** [comment]
Hi,

did that and seems to work now. Does not crash and dryer is added as expected. Great. :-) Thanks. 👍 

Garfonso
