### ISSUE TITLE
Can not start program from adapter

### ISSUE THREAD

**Issue by Garfonso** [dna909/ioBroker.homeconnect#18]
I failed to start the dryer remotly. I did set the active program in admin, but could not see an effect (it even stayed red, ie no ack).
In the logs I did see this message later:
"2019-07-15 17:37:36.802 - info: homeconnect.0 409: Request cannot be performed since OperationState is not DelayedStart, Run or Pause"
Not 100% sure this is related to not being able to start a program. Time could be right and it sounds a bit like it.
Do I have to manually set operation state, too? Or what does that mean?

Dryer was ready and all set (with remote execution enabled, I guess that is necessary for the adapter, too?) and I could start it from the smartphone app just fine.

**Comment by TA2k** [comment]
Try to reinstall via github and restart the instance. Select your option in program.selection and then select in program.active a program

**Comment by Garfonso** [comment]
Thanks for your help.

I updated the adapter from github and now it does not crash anymore.
But if I try to select a program I always get the error: "409: Option BSH.Common.Option.FinishInRelative not supported"
Why is that? At first try I did not change anything in the options. Then I tried to clear that option or set it to 0 and even tried to remove the object... but there does not seem to be a way to unset that option. 

I can still start the dryer fine from the app.... 

Any idea how to solve that?

**Comment by TA2k** [comment]
I tested this it looks like it is not supported by the API.
You can access the homeconnect developer to implement the feature to set this options.
https://developer.home-connect.com/support/contact

**Comment by Garfonso** [comment]
You mean it is not supported by the Api to start the dryer?

**Comment by TA2k** [comment]
I add a change whicht tries to activate a program without options when the program activation failed with options

**Comment by Garfonso** [comment]
Thanks for the quick update.

Sadly it still does not work. Now I get the following log output:
`2019-07-25 19:25:00.007  - info: javascript.0 script.js.otherSmarthome.Trockner: Starting LaundryCare.Dryer.Program.Cotton
2019-07-25 19:25:00.173  - info: homeconnect.0 409: Option BSH.Common.Option.FinishInRelative not supported
2019-07-25 19:25:00.340  - info: homeconnect.0 400: The request content was malformed:
Object is missing required member 'data'
`

**Comment by TA2k** [comment]
Please try again

**Comment by Garfonso** [comment]
Now it works, thank you very much.

**Comment by TA2k** [comment]
Can you send me the log?

**Comment by Garfonso** [comment]
I didn't have debug logging enabled, so in the log I only see the error:
2019-07-26 08:34:35.546  - info: homeconnect.0 409: Option BSH.Common.Option.FinishInRelative not supported
but after that the program started.

The program started with the options which were selected on the device and were set in program.selected.options.
