### ISSUE TITLE
Erstellung Datenpunkte für Zeitangabe/Dauer Wasch- und Trockengänge

### ISSUE THREAD

**Issue by AbdulAlBane** [dna909/ioBroker.homeconnect#20]
Gibt es die Möglichkeit, die verbleibende Zeit für die Wasch/Trockengänge der Geräte noch in einen Datenpunkt zu schreiben. In der App werden sie zusätzlich angezeigt, ggf. gibt die API das her? Ansonsten funktioniert der Adapter top!

**Comment by TA2k** [comment]
Meinst du sowas wie:
homeconnect.0.XXX.programs.active.options.BSH_Common_Option_RemainingProgramTime

**Comment by AbdulAlBane** [comment]
Ja, wobei der Datenpunkt bei mir nicht existiert. Der ganze "Options"-Zweig nicht... Habe die 0.22 am Laufen... Oder wird der erst erstellt, wenn tatsächlich ein Programm läuft?

**Comment by TA2k** [comment]
Wird erstellt wenn ein Programm aktiv ist.

**Comment by AbdulAlBane** [comment]
OK, danke.  Gerade getestet und funktioniert :) Wird der Zweig nach Abschluss des Programms wieder gelöscht oder werden die States darin dann korrekt auf 0 gesetzt (keine Restlaufzeit, Progress 100%)...

**Comment by TA2k** [comment]
Bisher wird von der API leider nur auf 99% 1min gesetzt.
Und der Adapter löscht es nicht wenn das Programm nicht mehr aktiv ist sondern nur wenn ein neues Programm aktiviert wird. Ich weiß nicht ob unter selected die Zeiten korrekt gesetzt werden.

**Comment by AbdulAlBane** [comment]
OK, dann löse ich das programmatisch. Und schließe das issue erstmal.
