### ISSUE TITLE
Usage of Event-Stream

### ISSUE THREAD

**Issue by neopholus** [dna909/ioBroker.homeconnect#21]
Hi,

I am using version 0.0.22 and the adapter is working ok usually, but there are some states the adapter does not catch, e.g. if I power off the dryer. Then the states show still e.g. "Finished" and settings.BSH_Common_Setting_PowerState still shows ON. I assume this is, because I power off and then the next poll does not receive any data and leaves all data as is.

In the objects I found dev.pollInterval = 30 seconds. Thus I think, the adapter is really polling the status from BSH.

I don't know how long the event stream is already available but some days ago I read [this](https://developer.home-connect.com/docs/general/bestpractices) and learned, that there is an event monitoring channel available. Thus, imho, it should be possible to switch from a poll to a push based adapter and detect events like a disconnect or a power off.

Are there any plans to use this  event monitoring channel?

Best regards
Stefan

**Comment by TA2k** [comment]
Hi,

the poll interval is no longer used. All data comes via event stream. When you set the log level on debug of the instance you should see the events coming from the API.

Please feel free to join the forum and post some images about the concrete states and log files:
https://forum.iobroker.net/topic/16446/aufruf-bsh-home-connect-adapter

**Comment by neopholus** [comment]
Thank you for the information. I will post images about the concrete states, but before I do a fresh reinstall and set debug level.
