### ISSUE TITLE
connected: false

### ISSUE THREAD

**Issue by Rambo79** [dna909/ioBroker.homeconnect#22]
My Coffeemaker is found by the adapter but under "general" connected has state "false"

No states are shown, so controlling by iobroker is still not possible.

**Comment by TA2k** [comment]
Is the device available in the home connect app?
Is the coffeemaker turned on?
You can set the instance in debug mode to see additional information.
You can try to reset the token
Or you can contact  https://developer.home-connect.com/support/contact for details.

**Comment by Rambo79** [comment]
Yes an Yes

Good Idea. First I'll try the debug mode.

**Comment by Rambo79** [comment]
I restarted the adapter turn the coffeemaker off and on again. Now it's working. Thx for help.

**Comment by Rambo79** [comment]
I dit the same again. Now it works. Thx for help. Issue can be closed.
