### ISSUE TITLE
0.0.22 keine Verbindung zu homeconnect

### ISSUE THREAD

**Issue by Peter1980FFM** [dna909/ioBroker.homeconnect#23]
Leider kann mann den Adapter nicht neu mit Homeconnect verbinden beim Besuchen der URL und des Anmelden kommt nur
![image](https://user-images.githubusercontent.com/45266139/65725824-d4795500-e0b3-11e9-8aef-780ae132f8ea.png)

**Comment by TA2k** [comment]
Die Homeconnect API ist zur Zeit instabil. In der Zeit sollten auch keine Token neuerstellt werden und Fehler können ignoriert werden. Einfach morgen nochmal probieren.

**Comment by TA2k** [comment]
Bitte auch alle Adapter immer updaten. Aktuell ist die 0.0.24
