### ISSUE TITLE
Kaffeevollautomat Zustand vom Milchbehälter

### ISSUE THREAD

**Issue by Knallix** [dna909/ioBroker.homeconnect#24]
Hallo,
 
ist es möglich bei der TI9555X1DE/10 // SIEMENS 
mit zu bekommen, ob der Milchgehälter noch gesteckt ist ?
Gibt es dafür einen State ? Wenn ich z.B. einen Milchkaffee mache und der Behälter ist nicht drin, dann meldet Sie mir das. 
Würde mich freuen, wenn es da etwas geben würde.

**Comment by TA2k** [comment]
Die Information werden von der API noch nicht zurückgegeben.
https://developer.home-connect.com/docs/monitoring/appliance_events
Du kannst auf Englisch den Wunsch äußern die Informationen aufzunehmen
https://developer.home-connect.com/support/contact
