### ISSUE TITLE
Adapter zeigt keine Warnmeldungen an

### ISSUE THREAD

**Issue by DirkLaurenz** [dna909/ioBroker.homeconnect#25]
Der Adapter zeigt keine Warnmeldungen an. Ich habe einen Siemens Geschirrspüler und es werden Warnmeldungen wie Salz alle oder Klarspüler nachfüllen nicht gezeigt. Habe ich da was falsch geamcht?

**Comment by TA2k** [comment]
Die Information werden von der API noch nicht zurückgegeben.
https://developer.home-connect.com/docs/monitoring/appliance_events
Du kannst auf Englisch den Wunsch äußern die Informationen aufzunehmen
https://developer.home-connect.com/support/contact
