### ISSUE TITLE
Changing baverage does not work with Coffee Machine ("BSH_Common_Root_SelectedProgram")

### ISSUE THREAD

**Issue by PatrickZ1990** [dna909/ioBroker.homeconnect#30]
The commands within "BSH_Common_Root_SelectedProgram" seem not to work for changing the program. The names of the programs are correct (I checked here https://developer.home-connect.com/docs/coffee-maker/supported_programs_and_options) and with "BSH_Common_Root_ActiveProgram" you can select and start the program at the same time. The problem is, that you can't customize the values within the beverage if the preselection is not possible. I tested it with an Siemens EQ9 S700.

**Comment by TA2k** [comment]
fixed in the new versions
