### ISSUE TITLE
"Bean amout option" missing in adapter

### ISSUE THREAD

**Issue by PatrickZ1990** [dna909/ioBroker.homeconnect#31]
The "Bean amount option" is currently missing in the selected.options section. It would be very important for customizing the baverages. For the commands please refer to https://developer.home-connect.com/docs/coffee-maker/bean_amount_option
Thank you very much for your work! :)

**Comment by TA2k** [comment]
Can you write me a direct message in the IoBroker forum. User tombox

**Comment by PatrickZ1990** [comment]
I wrote you a message :)

**Comment by OberfragGER** [comment]
i will do so as well. :)
