### ISSUE TITLE
Treshhold for Polling the Informations needs to be customizable -> The rate limit "1000 calls in 1 day" was reached

### ISSUE THREAD

**Issue by Netfreak25** [dna909/ioBroker.homeconnect#32]
homeconnect.0 | 2019-12-17 18:28:10.146 | info | (19197) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
-- | -- | -- | --
homeconnect.0 | 2019-12-17 18:28:10.143 | warn | (19197) Restart initiated
homeconnect.0 | 2019-12-17 18:28:08.412 | info | (19197) Accesstoken renewed...
homeconnect.0 | 2019-12-17 18:28:08.139 | warn | (19197) Restart the Adapter to get all devices correctly.
homeconnect.0 | 2019-12-17 18:28:08.138 | error | (19197) Error getting Aplliances with existing Token: 429 The rate limit "1000 calls in 1 day" was reached. Requests are blocked during the remaining period of 75840 seconds.
homeconnect.0 | 2019-12-17 18:28:07.839 | info | (19197) starting. Version 0.0.27 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v10.17.0
host.home-server | 2019-12-17 18:28:05.988 | info | instance system.adapter.homeconnect.0 started with pid 19197

**Comment by Netfreak25** [comment]
i've got two device which get checked by the instance and after half a day the instance stops due to the request restrictions

**Comment by TA2k** [comment]
Die Geräte senden eigentlich keine Request nur beim Start. Also scheint als würde der Adapter oft neugestartet werden? Kannst du mir im forum den kompletten Log zusenden?
