### ISSUE TITLE
CoffeeMaker_Event_WaterTankEmpty is not working

### ISSUE THREAD

**Issue by OberfragGER** [dna909/ioBroker.homeconnect#33]
Hi,
i own a BOSCH Coffeemachine an tried to trigger the event (Alexa shall tell about the events of the coffemachine).

The datapoint exists but it doesnt change. I set the adapter on debug, cleared the log an triggered the event. After the hot water - the event was on the machine itself but not in the item-section. please see the log attached.
https://pastebin.com/W9hzjkRH

@iobroker -tombox:
I will write you a message. i seen it also about the beanamount-issue.

**Comment by OberfragGER** [comment]
The watertankmessage is working when i shutdown the machine an the water is too less. But the warning is not working when the water runs low "in between".

**Comment by TA2k** [comment]
You should request this feature at the api developer to implement also an update event in between
https://developer.home-connect.com/support/contact
