### ISSUE TITLE
Error getting Aplliances with existing Token: 401 The access token expired

### ISSUE THREAD

**Issue by emeins** [dna909/ioBroker.homeconnect#35]
I cannot connect to my BSH API App from iobroker and get the following error messages:

homeconnect.0 | 2020-02-20 17:21:29.270 | info | (17870) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
homeconnect.0 | 2020-02-20 17:21:29.268 | info | (17870) terminating
homeconnect.0 | 2020-02-20 17:21:29.249 | info | (17870) cleaned everything up...
homeconnect.0 | 2020-02-20 17:21:29.246 | error | (17870) TypeError: this.stop is not a function at Adapter.restart (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:930:14) at Timeout.setTimeout [as _onTimeout] (/opt/iobroker
homeconnect.0 | 2020-02-20 17:21:29.244 | error | (17870) uncaught exception: this.stop is not a function
homeconnect.0 | 2020-02-20 17:21:29.230 | warn | (17870) Restart initiated
homeconnect.0 | 2020-02-20 17:21:27.242 | warn | (17870) Retry Refresh Token in 5min
homeconnect.0 | 2020-02-20 17:21:27.241 | error | (17870) Error Refresh-Token: 400 undefined
homeconnect.0 | 2020-02-20 17:21:27.228 | warn | (17870) If Restart is not working please reset the Token in the settings.
homeconnect.0 | 2020-02-20 17:21:27.227 | warn | (17870) Restart the Adapter to get all devices correctly.
homeconnect.0 | 2020-02-20 17:21:27.225 | error | (17870) Error getting Aplliances with existing Token: 401 The access token expired
homeconnect.0 | 2020-02-20 17:21:26.794 | info | (17870) starting. Version 0.0.26 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v10.19.0

**My environment:**
iobroker 4.0.3 (but got the same issue with latest stable version 3.7.8)
iob Home Connect plugin v0.0.26
Node 10.19.0 (but got the same issue with v8)

**BSH API is configured as described:**
![image](https://user-images.githubusercontent.com/17033201/74956566-997f1180-5406-11ea-9dd0-16ab563873ee.png)

![image](https://user-images.githubusercontent.com/17033201/74956659-b87da380-5406-11ea-88e6-2993e9cd87ce.png)

**Comment by TA2k** [comment]
Please try install via github link in adapters click on the github cat
https://github.com/dna909/ioBroker.homeconnect

**Comment by emeins** [comment]
Well I am a bit confused now. I installed v0.0.27 from git and was asked in the log to access an URL to authorized:
(21389) Please visit this url: https://verify.home-connect.com?user_code=3...
I tried this but always got the message:
![image](https://user-images.githubusercontent.com/17033201/75066556-59de2580-54eb-11ea-818a-e120773c3d5a.png)

Then I went back to v0.0.26, was asked again to access an oauth URL and it worked well after authorization.

I can see my dishwasher now in iobroker but no clue why it is working now, same Client ID.
In between I also enabled the One Time Token on the API side, but now idea if there is any impact.
![image](https://user-images.githubusercontent.com/17033201/75066878-1e902680-54ec-11ea-87af-dbcb4fba6fc5.png)

**Comment by TA2k** [comment]
sometimes home connect has also some issues can you remove the instance and reinstall the 0.27 to check if this version is working for you

**Comment by emeins** [comment]
Ok, just updated to v0.0.27. It is also working well.

**Comment by emeins** [comment]
Thx for your support, I also assume something happened on the BSH side.
