### ISSUE TITLE
property error

### ISSUE THREAD

**Issue by arteck** [dna909/ioBroker.homeconnect#37]
![grafik](https://user-images.githubusercontent.com/6681528/80461318-63de3380-8935-11ea-88a3-a357acc144c7.png)

**Comment by TA2k** [comment]
Ich habe ml den eror log verbessetr. einfach über github installiern und neustarten und mir den log via iobroker forum per pn schicken

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/80569775-e6c8c200-89f9-11ea-99fb-b33f51f99cb1.png)

**Comment by TA2k** [comment]
should be fixed in 0.0.13
