### ISSUE TITLE
wartezeit nach restart 

### ISSUE THREAD

**Issue by arteck** [dna909/ioBroker.homeconnect#38]
![grafik](https://user-images.githubusercontent.com/6681528/80562731-dc51fc80-89e8-11ea-9792-72a676ce0284.png)

es währe hilfreich eine option einzubauen das der adapter erst nach 10 min startet bei dem Fehler

**Comment by TA2k** [comment]
Der Fehler sollte nicht komme.  Wann tritt er bei dir auf

**Comment by arteck** [comment]
nach einem Timeout.. zb. wenn ich ein reconnect mache

**Comment by TA2k** [comment]
Wer oder was timed genau aus. Wie machst du ein reconnect und wie oft

**Comment by OberfragGER** [comment]
Moin, ich bekomme das nachdem die 1.000 erlaubten APi-Aufrufe pro Tag überschritten sind. Dann heisst es - 1nen Tag warten.

Doof wenn man viele Bosch Geräte hat, weil dadurch mehr Api-Aufrufe.

**Comment by TA2k** [comment]
eigentlich sollte das nicht passieren denn status übertragen ist kein api aufruf. Starten des Adapters und geräte bedienen sind api calls.
bitte neuste version des adapters installieren und checken ob es noch passiert

**Comment by OberfragGER** [comment]
okay. habe ich gemacht. ich mache dann einissue auf, wenn ich immer noch gesperrt werde.
