### ISSUE TITLE
Tassenwärmer steuern

### ISSUE THREAD

**Issue by lindi200000** [dna909/ioBroker.homeconnect#39]
Hallo,
ist es möglich über einen Datenpunkt den Tassenwärmer anzuschalten? 
In der HomeConnect App ist das an und abschalten möglich, währe super wenn man das auch über IOBroker machen könnte.

VG
Lindi

**Comment by TA2k** [comment]
Das Gerät ist noch nicht unterstützt
https://developer.home-connect.com/docs/monitoring/appliance_state_changes
du kannst hier nachfragen das sie es aufnehmen
https://developer.home-connect.com/support/contact

**Comment by lindi200000** [comment]
Danke für die Info, Anfrage ist erstellt :)
