### ISSUE TITLE
1000 calls in 1 day limit reached

### ISSUE THREAD

**Issue by OberfragGER** [dna909/ioBroker.homeconnect#41]
Hi,

ich habe einige Homeconnect Geräte.
Kaffeemaschine. Ofen, Herd, Dunstabzugshaube.

Installiert ist der aktuellste Adapter. Leider erreiche ich jeden 2. Tag das Limit von 1000 API-calls. Ich habe mal auf Debug gestellt und das Log hierhin kopiert.

https://pastebin.com/UGqpu8k8

Was kann ich machen um die API-Calls zu reduzieren?

**Comment by TA2k** [comment]
Ich benötige den log im debug wenn das limit noch nicht erreicht hast.
Einfach adapter deaktivieren ein tag warten. Adapter Instanz auf debug stellen und mit den log auch per pn im forum senden. du kannst auch mal den token in den instanz optionen zurückzusetzen

**Comment by OberfragGER** [comment]
Wird so gemacht. Jetzt erstmal paar Sekunden warten.

**Comment by OberfragGER** [comment]
Scheint nun zu funktionieren.

**Comment by OberfragGER** [comment]
Scheint nun keine PRobleme mehr zu machen.
