### ISSUE TITLE
Activation URL

### ISSUE THREAD

**Issue by firelook** [dna909/ioBroker.homeconnect#42]
Hi,
I try to config the module .
I put the right code for client_id, but I have nothing in the Activation URL
If I press the button " AUTH URL BESUCHEN" => I have nothing

help please ?

**Comment by TA2k** [comment]
enter the client_id press save and exit.
wait until the instance is green visit the options again

**Comment by firelook** [comment]
it never switch to green

**Comment by TA2k** [comment]
The homeconnect api has server issues at the moment. you should try it tomorrow or monday again.

**Comment by firelook** [comment]
this morning it is working , thanks for your help
