### ISSUE TITLE
Bosch Trockner lässt sich nicht steuern.

### ISSUE THREAD

**Issue by mane444** [dna909/ioBroker.homeconnect#56]
Hallo, bei mir lässt sich leider der Trockner nicht steuern. Wenn ich auf den Button Pause drücke geht der Trockner zwar aus, er zeigt aber nicht Pause am Display.
Wenn ich den Button Resume drücke passiert nichts. Es wird im Log folgende Meldung ausgegeben.
409: Request cannot be performed since OperationState is not DelayedStart, Run or Pause

Mache ich hier einen Fehler, oder muss ich noch Einstellungen anpassen ?

**Comment by TA2k** [comment]
fix in 0.0.31
