### ISSUE TITLE
The access token expired

### ISSUE THREAD

**Issue by firelook** [dna909/ioBroker.homeconnect#8]
`

homeconnect.0 | 2019-01-10 15:47:12.421 | error | Irgendwas stimmt da wohl nicht!! Token!! Fehlercode: 401,The access token expired
-- | -- | -- | --
homeconnect.0 | 2019-01-10 15:47:12.165 | info | starting. Version 0.0.6 in C:/iobroker/node_modules/iobroker.homeconnect, node: v6.11.3
host.Obelix | 2019-01-10 15:47:10.275 | info | instance system.adapter.homeconnect.0 started with pid 2908
host.Obelix | 2019-01-10 15:47:07.775 | info | instance system.adapter.homeconnect.0 terminated with code null ()
host.Obelix | 2019-01-10 15:47:07.775 | warn | instance system.adapter.homeconnect.0 terminated due to SIGTERM
host.Obelix | 2019-01-10 15:47:07.752 | info | stopInstance system.adapter.homeconnect.0 killing pid 12068
host.Obelix | 2019-01-10 15:47:07.752 | info | stopInstance system.adapter.homeconnect.0
host.Obelix | 2019-01-10 15:47:07.749 | info | object change system.adapter.homeconnect.0
homeconnect.0 | 2019-01-10 13:57:19.829 | error | Irgendwas stimmt da wohl nicht!! Token!! Fehlercode: 401,The access token expired
homeconnect.0 | 2019-01-10 13:57:19.529 | info | starting. Version 0.0.6 in C:/iobroker/node_modules/iobroker.homeconnect, node: v6.11.3
host.Obelix | 2019-01-10 13:57:18.077 | info | instance system.adapter.homeconnect.0 started with pid 12068
mqtt-client.0 | 2019-01-10 13:57:16.892 | info | connected to broker
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | Try to connect to mqtt://127.0.0.1:1883?clientId=iobroker with lwt
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Event.ProgramFinished (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Event.ProgramAborted (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Option.RemainingProgramTime (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Option.ProgramProgress (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Option.StartInRelative (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.776 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Root.SelectedProgram (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.775 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Root.ActiveProgram (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.775 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Status.OperationState (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.775 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Status.DoorState (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.774 | info | enabled syncing of homeconnect.0.SIEMENS-SN778D16TE-68A40E23A59D.Setting.PowerState (publish/subscribe:true/false)
mqtt-client.0 | 2019-01-10 13:57:16.754 | info | starting. Version 1.1.1 in C:/iobroker/node_modules/iobroker.mqtt-client, node: v6.11.3
admin.0 | 2019-01-10 13:57:15.827 | info | Repository received successfully.
host.Obelix | 2019-01-10 13:57:15.254 | info | instance system.adapter.mqtt-client.0 started with pid 11536
host.Obelix | 2019-01-10 13:57:13.749 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
admin.0 | 2019-01-10 13:57:13.662 | info | Use link "http://localhost:8081" to configure.
admin.0 | 2019-01-10 13:57:13.661 | info | http server listening on port 8081
admin.0 | 2019-01-10 13:57:13.595 | info | received all objects
admin.0 | 2019-01-10 13:57:13.372 | info | received all states
admin.0 | 2019-01-10 13:57:13.211 | info | Request actual repository...
admin.0 | 2019-01-10 13:57:13.210 | info | requesting all objects
admin.0 | 2019-01-10 13:57:13.209 | info | requesting all states
admin.0 | 2019-01-10 13:57:13.194 | info | starting. Version 3.5.10 in C:/iobroker/node_modules/iobroker.admin, node: v6.11.3

`

seems after a reboot, or a problem (perhaps) can not manage to reconnect or re create a token

**Comment by dna909** [comment]
the token-refresh does not work properly yet. In this case simply set the data point 'access' under dev to false and restart the adapter.
Then the authorization process starts again. Then it should run again.
I will take care of the problem soon.

dna909

**Comment by firelook** [comment]
yes it works ! but I have to regrant everything ;)
seems you are right, not working properly ( yet ;) )

**Comment by PetEile** [comment]
In main.js in function receive() before "Most likely the token has expired, try to refresh the token" just add the code attached. You will still receive some errors if you have more than one homeappliance (Bad request for all but first). But the token will be refreshed.
[TokenRefresh.txt](https://github.com/dna909/ioBroker.homeconnect/files/2807372/TokenRefresh.txt)

**Comment by PetEile** [comment]
What do you mean with Standard Code?

Am Di., 29. Jän. 2019, 14:27 hat firelook <notifications@github.com>
geschrieben:

**Comment by firelook** [comment]
in your master branch on github
